### ISSUE TITLE
Tạo kịch bản hỏi đáp

### ISSUE THREAD

**Issue by yuvayt** [Y2eVen/SE04-Nhom24.2#13]
Tạo kịch bản hỏi đáp thay thế cho form: [https://docs.google.com/forms/d/e/1FAIpQLSf1AfCgMBN2dPf21hXomdK9pFiSAfrN0x12IBlLmbBzitdh3g/viewform?fbclid=IwAR1_C3NtcQCjd4OJbW8nP1_JI_PsTdBEBwP0ai46M_LbkDScAYulS06CUeE](url)

**Comment by hao-prog** [comment]
sao bấm vào link nó ko mở file docs lên nhỉ

**Comment by yuvayt** [comment]
Có lẽ là do link t đưa lên lỗi, để t ném cái khác lên

**Comment by hao-prog** [comment]
OK

**Comment by yuvayt** [comment]
À ko t vừa thử r ae đừng click vào link mà copy link r cho vào thanh địa chỉ là mở được

**Comment by hao-prog** [comment]
Ohhhhhh
