### ISSUE TITLE
Cài đặt cho bot hỏi theo kịch bản

### ISSUE THREAD

**Issue by hao-prog** [Y2eVen/SE04-Nhom24.2#29]

**Comment by hao-prog** [comment]
T có ý tưởng là tạo 1 mảng, hỏi các câu hỏi theo thứ tự và lưu lại các câu trả lời theo thứ tự vào mảng đó. Mỗi 1 lần bot định hỏi thì sẽ duyệt từ đầu mảng đến cuối xem phần tử nào đang trống và tương ứng với câu hỏi nào thì hỏi câu hỏi đó.

**Comment by yuvayt** [comment]
Hoặc là mình có thể tạo object form cũng được rồi rút gọn các thuộc tính xuống để phù hợp với database, mình cũng có thể check thuộc tính nào còn trống để them vào.

**Comment by hao-prog** [comment]
Uh thế ae mình cứ thử làm từng cách rồi bàn luận xem dùng cách nào ổn hơn nhé
