### ISSUE TITLE
Lưu các câu trả lời của người dùng vào DataBase

### ISSUE THREAD

**Issue by hao-prog** [Y2eVen/SE04-Nhom24.2#30]

**Comment by yuvayt** [comment]
Do mình dùng server của Heroku nên t nghĩ mình sẽ dùng luôn PostgreSQL của Heroku

**Comment by hao-prog** [comment]
Ok, t cũng đã tìm hiểu thử và thấy kết nối với PostgreSQL của Heroku khá dễ dàng

**Comment by hao-prog** [comment]
T đã tìm hiểu được cách thêm PostgreSQL vào app của mình trên Heroku:
![image](https://user-images.githubusercontent.com/72394775/103174342-e2f48480-4893-11eb-877e-52a50704358b.png)
-------------------

**Comment by hao-prog** [comment]
Còn đây là cách kết nối và thực hiện truy vấn trong code:
![image](https://user-images.githubusercontent.com/72394775/103174321-b5a7d680-4893-11eb-9485-b80a5eaa36d8.png)
-------------------

**Comment by hao-prog** [comment]
Mình sẽ lưu tầm 30 câu trả lời của mỗi người dùng thì không biết có nên tạo 1 table 30 cột ko nhỉ

**Comment by yuvayt** [comment]
t mới đọc thì limit của row là 10000 còn limit của column là bnh thì nó ko nói

**Comment by hao-prog** [comment]
T vừa thử tạo 1 bảng 30 cột trên link này: https://extendsclass.com/postgresql-online.html thì nó bị lỗi ae ạ. Chắc phải nghĩ cách khác thôi

**Comment by hao-prog** [comment]
T đã kiểm tra cẩn thận về cú pháp rùi mà vẫn lỗi
![image](https://user-images.githubusercontent.com/72394775/103186586-b53f2800-48f3-11eb-982f-c7ca020427af.png)
![image](https://user-images.githubusercontent.com/72394775/103187220-28e23480-48f6-11eb-91e6-bdf32b9ad906.png)
