### ISSUE TITLE
Giá trị của biến global thay đổi không như ý muốn

### ISSUE THREAD

**Issue by hao-prog** [Y2eVen/SE04-Nhom24.2#31]
![image](https://user-images.githubusercontent.com/72394775/103173000-63ae8300-488a-11eb-90b9-8bd8a772f27d.png)
--------------------
T có 1 biến đếm để mỗi khi người dùng nhắn tin thì nó tăng lên 1 đơn vị.
![image](https://user-images.githubusercontent.com/72394775/103173033-9c4e5c80-488a-11eb-9def-53058dafd053.png)
-----------------------
Nhưng mà t kiểm tra thì lại thấy nó tăng lên 2... Có ae nào có solution ko?????

**Comment by yuvayt** [comment]
M thử check xem có chỗ nào gọi đến hàm này 2 lần ko

**Comment by hao-prog** [comment]
T check lại cẩn thận và kĩ lắm rồi, hàm xử lý tin nhắn chỉ còn mỗi chức năng là tăng biến đó lên 1 mà vẫn bị lỗi.

**Comment by yuvayt** [comment]
Hoặc cũng có thể biến của m là global nên nó đã bị gọi đến và tăng lên ở đâu đó mà ko nhất thiết gọi đến hàm xử lí tin nhắn

**Comment by hao-prog** [comment]
T thử đổi tên biến và những chỗ liên quan nhưng nó vẫn thế... để t kiểm tra xem có phải do bug của cái j đấy khiến hàm này bị gọi 2 lần khi người dùng gửi tin nhắn ko...

**Comment by yuvayt** [comment]
T nghĩ khả năng bị bug là ít t nghĩ có thể liên quan đến cơ chế nhận diện tinh nhắn của chatbot

**Comment by hao-prog** [comment]
Hmm cũng có lý, để t thử check xem tin nhắn của bot khi gửi thì có chạy hàm handleMessage() ko...

**Comment by hao-prog** [comment]
T check rùi, hóa ra là khi người dùng gửi tin nhắn thì bot cũng sẽ gửi lại 1 tin nhắn nên hàm handleMessage() bằng cách nào đó được chạy 2 lần. Bot handle chính message của mình luôn :)))

**Comment by yuvayt** [comment]
T cũng vừa mới tìm ra đang test lại cho chắc có lẽ mình sẽ cần thêm điều kiện để loại bỏ tin nhắn của bot hoặc, ko xử lí tin nhắn của bot

**Comment by hao-prog** [comment]
Để giải quyết vấn đề này thì t đang nghĩ đến cách là chỉ handleMessage() khi id của sender ko phải id của bot, vì t thấy console log phần tin nhắn gửi đi của bot thì bot cũng có 1 id cố định.

**Comment by hao-prog** [comment]
> Để giải quyết vấn đề này thì t đang nghĩ đến cách là chỉ handleMessage() khi id của sender ko phải id của bot, vì t thấy console log phần tin nhắn gửi đi của bot thì bot cũng có 1 id cố định.

T đã thử làm theo cách này và không bị lỗi nữa rồi nhé ae ^^.
Đây là cách t fix lỗi:
![image](https://user-images.githubusercontent.com/72394775/103174793-872bfa80-4897-11eb-8164-a537ed22d120.png)

----------------

**Comment by hao-prog** [comment]
> > Để giải quyết vấn đề này thì t đang nghĩ đến cách là chỉ handleMessage() khi id của sender ko phải id của bot, vì t thấy console log phần tin nhắn gửi đi của bot thì bot cũng có 1 id cố định.
> 
> T đã thử làm theo cách này và không bị lỗi nữa rồi nhé ae ^^.
> Đây là cách t fix lỗi:
> ![image](https://user-images.githubusercontent.com/72394775/103174793-872bfa80-4897-11eb-8164-a537ed22d120.png)

Trong đó 113168717253257 là id của bot mình có thể tìm thấy ở console nha.
