### ISSUE TITLE
Mình sẽ lưu tầm 30 câu trả lời của mỗi người dùng thì không biết có nên tạo 1 table 30 cột ko nhỉ

### ISSUE THREAD

**Issue by hao-prog** [Y2eVen/SE04-Nhom24.2#32]
Mình sẽ lưu tầm 30 câu trả lời của mỗi người dùng thì không biết có nên tạo 1 table 30 cột ko nhỉ

_Originally posted by @hao-prog in https://github.com/Y2eVen/SE04-Nhom24.2/issues/30#issuecomment-751483133_

**Comment by yuvayt** [comment]
T thử tạo thì có vẻ là tạo được 30 cột đấy nhưng t vẫn chưa rõ tại sao m lại sai 
![image](https://user-images.githubusercontent.com/68575750/103194557-9bf9a400-4912-11eb-8a71-fdafebeb7f07.png)

**Comment by yuvayt** [comment]
Cậu có thể ném code cậu tạo table lên được ko?

**Comment by hao-prog** [comment]
create table scientist (Tên text, Đại_diện text, SĐT bigint, Email text, LinkFB text, Cần_thông_tin_về_địa_phương_chịu_thiệt_hại_nhất_và_chưa_được_hỗ_trợ_nhiều integer, Cần_danh_sách_các_hoàn_cảnh_bị_thiệt_hại_và_cần_được_hỗ_trợ_xác_minh_các_trường_hợp_này integer, Cần_kết_nối_với_chính_quyền_và_các_tổ_chức_tại_địa_phương integer, Cần_kết_nối_với_tình_nguyện_viên_hoặc_tổ_chức_từ_thiện_khác_ở_cùng_khu_vực integer, Cần_hỗ_trợ_chuyển_tiền_và_hàng_cứu_trợ_đến_tận_tay_người_được_cứu_trợ integer, Cần_truyền_thông_để_huy_động_được_nhiều_hơn integer, Cần_hỗ_trợ_bằng_hình_thức_khác text, Gửi_tiền integer, Gửi_hàng integer, Hỗ_trợ_lâu_dài integer, Hình_thức_cứu_trợ_khác text, Ưu_tiên_Bất_cứ_ai_có_hoàn_cảnh_khó_khăn integer, Ưu_tiên_Người_già integer, Ưu_tiên_Người_bệnh integer, Ưu_tiên_Trẻ_em integer, Ưu_tiên_Nông_dân integer, Ưu_tiên_Ngư_dân integer, Ưu_tiên_Trường_học integer, Ưu_tiên_Cơ_sở_Y_tế integer, Ưu_tiên_Xây_dựng_hạ_tầng(điện_đường_trường_trạm) integer, Ưu_tiên_Cung_cấp_nước_sạch_và_vệ_sinh_sạch integer, Ưu_tiên_Cung_cấp_nhà_an_toàn_trong_lũ integer, Ưu_tiên_đối_tượng_khác text, Chia_sẻ_Các_dữ_liệu_các_hoàn_cảnh_hoặc_hộ_cần_cứu_trợ_mà_bạn_có integer, Chia_sẻ_Sau_khi_cứu_trợ_và_chia_sẻ_hình_ảnh_và_thông_tin_đã_cứu_trợ_với_chúng_tôi integer, Chia_sẻ_Tham_gia_tình_nguyện_viên_cùng_chiến_dịch integer, Chia_sẻ_Ý_tưởng_và_Đề_xuất_khác_với_cộng_đồng text);
---------------------
Nó đây...

**Comment by yuvayt** [comment]
Oh, nó sai do trong tên ko được chứa dấu đóng ngoặc mở ngoặc đó, đây nè bỏ đi là được
![image](https://user-images.githubusercontent.com/68575750/103195057-0d862200-4914-11eb-94e0-9406f86ff9c5.png)

**Comment by hao-prog** [comment]
> Oh, nó sai do trong tên ko được chứa dấu đóng ngoặc mở ngoặc đó, đây nè bỏ đi là được
> ![image](https://user-images.githubusercontent.com/68575750/103195057-0d862200-4914-11eb-94e0-9406f86ff9c5.png)

Oh okay, t thử bỏ cặp () ở tên cột đó thì nó hết lỗi rùi nè
