### ISSUE TITLE
Sử dụng bảng 10 cột hay 30 cột trong Database

### ISSUE THREAD

**Issue by yuvayt** [Y2eVen/SE04-Nhom24.2#33]
****

**Comment by yuvayt** [comment]
Bảng 30 thì có thì tuy nó nhiều cột và nếu lỗi thì mất khá nhiều thời gian để sửa nhưng t thấy nó khá rõ ràng và chi tiết.

**Comment by yuvayt** [comment]
Để dễ hình dung thì 30 cột nó sẽ như thế này
![image](https://user-images.githubusercontent.com/68575750/103196998-c732c200-4917-11eb-9485-fc3e7a24cf4e.png)

**Comment by hao-prog** [comment]
T thì thấy bảng 10 cột thì trông khá gọn gàng và có thể tiết kiệm đc thời gian truy vấn

**Comment by hao-prog** [comment]
Câu lệnh truy vấn và table trông chỉ như thế này thui:
![image](https://user-images.githubusercontent.com/72394775/103197161-21cc1e00-4918-11eb-8be7-1138542c0086.png)

**Comment by ngochuy-1012** [comment]
Bảng 10 cột liệu có đầy đủ được hết các thông tin cần thu thập không nhỉ

**Comment by hao-prog** [comment]
> Bảng 10 cột liệu có đầy đủ được hết các thông tin cần thu thập không nhỉ

Có chứ, ví dụ đối với câu hỏi này thì mình sẽ lưu các câu trả lời của user như sau: "Có" tương đương với "1", "Không" tương đương với "0", ý kiến khác thì giữ nguyên text của user và nối chúng lại thành 1 string theo đúng thứ tự câu trả lời tương ứng trong form.
-----------------
![image](https://user-images.githubusercontent.com/72394775/103198169-4628fa00-491a-11eb-8ae8-b3a457bc6c2e.png)

**Comment by hao-prog** [comment]
> > Bảng 10 cột liệu có đầy đủ được hết các thông tin cần thu thập không nhỉ
> 
> ## Có chứ, ví dụ đối với câu hỏi này thì mình sẽ lưu các câu trả lời của user như sau: "Có" tương đương với "1", "Không" tương đương với "0", ý kiến khác thì giữ nguyên text của user và nối chúng lại thành 1 string theo đúng thứ tự câu trả lời tương ứng trong form.
> ![image](https://user-images.githubusercontent.com/72394775/103198169-4628fa00-491a-11eb-8ae8-b3a457bc6c2e.png)

Mỗi cột sẽ chứa đủ thông tin cho câu hỏi tương ứng

**Comment by yuvayt** [comment]
Nhưng nếu cần sử dụng thông tin thì t nghĩ hơi bất tiện trừ khi mình có cách để lưu nó vẫn ngắn gọn mà vẫn đầy đủ nội dung

**Comment by GoiLaHoan** [comment]
T vẫn nghĩ nên để 30 column thì tốt hơn, nhìn thế thôi chứ nhìn bảng cũng k rối lắm.
Nhưng 30 column thì nên cẩn thận vì lỗi thì mất thời gian để fix

**Comment by GoiLaHoan** [comment]
> T vẫn nghĩ nên để 30 column thì tốt hơn, nhìn thế thôi chứ nhìn bảng cũng k rối lắm.
> Nhưng 30 column thì nên cẩn thận vì lỗi thì mất thời gian để fix

Và để 30 column thì dễ dàng lấy thông tin hơn, cũng không phải  mất công phân tích "1" hay "0" như của @hao-prog

**Comment by yuvayt** [comment]
t nghĩ là để 10 cũng đc rồi mình thay các câu trả lời từ 1 thành các câu đơn giản như ở cột "yêu cầu hỗ trợ" nếu cần kết nối với chính quyền thì mình ghi là ""kết nối với chính quyền", còn nếu ko đồng ý thì ko phai ghi, nếu ko có ý kiến khác thì cũng ko phải ghi

**Comment by hao-prog** [comment]
> t nghĩ là để 10 cũng đc rồi mình thay các câu trả lời từ 1 thành các câu đơn giản như ở cột "yêu cầu hỗ trợ" nếu cần kết nối với chính quyền thì mình ghi là ""kết nối với chính quyền", còn nếu ko đồng ý thì ko phai ghi, nếu ko có ý kiến khác thì cũng ko phải ghi

uh t thấy cách này cũng ổn đó.
