### ISSUE TITLE
Làm sao để xem Database.

### ISSUE THREAD

**Issue by hao-prog** [Y2eVen/SE04-Nhom24.2#35]

**Comment by hao-prog** [comment]
T mới chỉ có cách này để xem DB thôi nhưng thấy không đẹp lắm. Có ae nào có cách gì hay hơn ko????
------------------
![image](https://user-images.githubusercontent.com/72394775/103213735-2e18a100-4941-11eb-82e1-d8e775c401c9.png)

![image](https://user-images.githubusercontent.com/72394775/103213724-25c06600-4941-11eb-9134-a1f8bfda0b30.png)

**Comment by GoiLaHoan** [comment]
Đưa db lên excel có được không?
https://www.brcline.com/blog/how-to-write-an-excel-file-in-nodejs
Tham khảo thử này xem có đúng ý không nhỉ?

**Comment by GoiLaHoan** [comment]
> Đưa db lên excel có được không?
> https://www.brcline.com/blog/how-to-write-an-excel-file-in-nodejs
Tham khảo thử này xem có đúng ý không nhỉ?

**Comment by hao-prog** [comment]
Uh trông cũng có vẻ ổn đấy. Để t xem còn cách nào khác ko, ko thì dùng cách này.

**Comment by hao-prog** [comment]
T mới tìm được cách này cũng xem được DB của mình nè: Vào link này https://heroku-data-explorer.herokuapp.com/#/

**Comment by hao-prog** [comment]
Đăng nhập rồi chọn app là xem được
![image](https://user-images.githubusercontent.com/72394775/103288833-60490200-4a18-11eb-9cd6-41a2343fbb2c.png)

**Comment by hao-prog** [comment]
> T mới tìm được cách này cũng xem được DB của mình nè: Vào link này https://heroku-data-explorer.herokuapp.com/#/

Tạm thời dùng cách này nhé, còn lâu dài thì dùng cách excel của Hoàn vì cách xem của heroku nó cho dùng thử 7 ngày thôi :v
