### ISSUE TITLE
Bug Câu hỏi bị lặp lại khi ý định của user là "Không"

### ISSUE THREAD

**Issue by hao-prog** [Y2eVen/SE04-Nhom24.2#36]
![image](https://user-images.githubusercontent.com/72394775/103294639-d2274880-4a24-11eb-8479-c128a55b8864.png)
-----------------
Ae có cách fix bug này ko....

**Comment by yuvayt** [comment]
Có thể là do wit.ai chăng, thế khi trả lời là 'Có' thì có được ko m

**Comment by hao-prog** [comment]
Trả lời "Có" thì t thấy vẫn bình thường
-------------------
![image](https://user-images.githubusercontent.com/72394775/103295352-562e0000-4a26-11eb-938b-084cd81d6e5b.png)

**Comment by GoiLaHoan** [comment]
![image](https://user-images.githubusercontent.com/67900737/103295805-54187100-4a27-11eb-92d2-b57b8325205d.png)
T sửa lại !ansArr[5] thay bằng ansArr[5] == null, thì không thấy lặp lại nữa, t nghĩ thế này chắc là đúng rồi đấy

**Comment by yuvayt** [comment]
Lạ nhỉ, à chắc là do cái này nên khi câu sau xét !ansArr[x] sẽ bị lỗi
![image](https://user-images.githubusercontent.com/68575750/103296054-d99c2100-4a27-11eb-8725-b9e27b9ab68a.png)
do '' nó ko xét là tồn tại object nhưng nó không null

**Comment by yuvayt** [comment]
> ![image](https://user-images.githubusercontent.com/67900737/103295805-54187100-4a27-11eb-92d2-b57b8325205d.png)
> T sửa lại !ansArr[5] thay bằng ansArr[5] == null, thì không thấy lặp lại nữa, t nghĩ thế này chắc là đúng rồi đấy

Có j m sửa r commit lên luôn nhé

**Comment by GoiLaHoan** [comment]
Done rùi
