### ISSUE TITLE
Nhận diện tên tổ chức

### ISSUE THREAD

**Issue by hao-prog** [Y2eVen/SE04-Nhom24.2#37]
T test thử NER của underthesea thì thấy mới nhận diện được ít tên tổ chức quá, chỉ mỗi Bộ Công Thương, Bộ Giáo Dục, ...
Ae có ý tưởng gì ko???

**Comment by GoiLaHoan** [comment]
Nhảy sang wit.ai thử xem

**Comment by yuvayt** [comment]
Bên vncore thì có vẻ nhận diện được nhiều tổ chức hơn nhưng nó mất khá nhiều thời gian, nên t cũng nghĩ là mình thử train wit.ai

**Comment by GoiLaHoan** [comment]
https://wit.ai/apps/673596706642835/entities/239684634234613
mọi người vào đây thêm các tên tổ chức nha
