### ISSUE TITLE
Chèn biến vào query string với DB

### ISSUE THREAD

**Issue by hao-prog** [Y2eVen/SE04-Nhom24.2#38]
T đang gặp lỗi khi chèn biến vào query string như sau, ae có cách fix thì bảo t với nhé
![image](https://user-images.githubusercontent.com/72394775/103298622-4fef5200-4a2d-11eb-94e9-c1ed69cc15ef.png)
![image](https://user-images.githubusercontent.com/72394775/103298645-5da4d780-4a2d-11eb-9c2c-c40e1c043764.png)
![image](https://user-images.githubusercontent.com/72394775/103298678-6c8b8a00-4a2d-11eb-874a-3d9e95fe0536.png)
---------------

**Comment by yuvayt** [comment]
Hay m quên chưa tạo cột hovaten vì t thấy nó báo ko tồn tại cột này

**Comment by hao-prog** [comment]
Hmmm, t cũng ko biết nữa, t tạo bảng chỉ có 3 cột là "Tên", "Đại_diện" và "SĐT" rồi insert 3 giá trị tương ứng 3 cột thui mà, sao nó lại bảo column "hovaten" nhỉ...

**Comment by hao-prog** [comment]
T mới phát hiện ra là nếu t insert ntn thì nó lại ko có lỗi gì cơ:
![image](https://user-images.githubusercontent.com/72394775/103329040-a2605b00-4a8d-11eb-88b8-337b2bcec9c1.png)

**Comment by yuvayt** [comment]
À cái này là do m để các biến dưới dạng text nên khi m truyền biến vào cũng phải ở dạng text ở trên nó sai do m viết sai cú pháp format của js thôi bh m chỉ cần viết là '${...}' là được.

**Comment by hao-prog** [comment]
Ồ ra là vậy, t thử lại theo cách m thì chạy oke r nhé
