### ISSUE TITLE
Nhận diện tên tổ chức

### ISSUE THREAD

**Issue by hao-prog** [Y2eVen/SE04-Nhom24.2#41]
T mới phát hiện ra bot wit.ai của mình đang nhận diện nhầm tên người thành tên tổ chức:
-------------
![image](https://user-images.githubusercontent.com/72394775/103355365-a1a4e480-4ae0-11eb-9c84-a6c9e687c017.png)

**Comment by hao-prog** [comment]
T đang nghĩ mình cần train thêm cho bot về những trường hợp không phải là tên tổ chức để bot hiểu rõ hơn để ko bị nhầm nữa...

**Comment by hao-prog** [comment]
Với cả có khi trong code giờ phải check confidence của những thứ bot đoán >= 0.8 cho chắc vì t thấy có mấy lần bot dự đoán ko đúng nhưng confidence vẫn tầm 0.7

**Comment by yuvayt** [comment]
T cũng đã thêm một Entity nữa cho tên người để bot có thể phân biệt được
