### ISSUE TITLE
Vấn đề truy cập biến global

### ISSUE THREAD

**Issue by hao-prog** [Y2eVen/SE04-Nhom24.2#42]
T và Thế Anh cùng chat với bot thì thấy các câu hỏi ko đúng kịch bản và DB hiện ra thì lưu cả thông tin của T và Thế Anh, t đang nghĩ có thể mảng lưu các câu trả lời của người dùng đang bị dùng chung bởi t và Thế Anh, cần phải làm cách nào đó để mỗi người dùng có 1 mảng riêng lưu các câu trả lời của họ.

**Comment by yuvayt** [comment]
Hiện tại thì bug đã được xử lí bằng cách sử dụng json và mỗi lần có người muốn ủng hộ thì sẽ tại add thêm 1 object với key là id của người gửi và value là 1 mảng chứa câu trả lời câu hỏi của người dùng.
