### ISSUE TITLE
Enhance Chatbot with AI

### ISSUE THREAD

**Issue by yuvayt** [Y2eVen/SE04-Nhom24.2#5]

**Comment by yuvayt** [comment]
Mình có thể sẽ dùng underthesea để kiểm tra tên người cũng như tên các tổ chức ở VN

**Comment by hao-prog** [comment]
Anh Thành có bảo mình dùng fasttex để train bot đoán intent(ý định) của user nhưng t đọc thấy khó hiểu quá .T đang thử dùng wit.ai của Facebook để train bot đoán ý định của người dùng trong câu nói và thấy ổn phết ae ạ.
----------------
![image](https://user-images.githubusercontent.com/72394775/103173579-7e82f680-488e-11eb-808c-228914701d57.png)

**Comment by hao-prog** [comment]
> Mình có thể sẽ dùng underthesea để kiểm tra tên người cũng như tên các tổ chức ở VN

làm sao để dùng underthesea thế cậu??????

**Comment by yuvayt** [comment]
Chỉ cần có 1 file requeriment.txt của underthesea và runtime.txt cho python là được r cậu, xong mình có thể xây dựng riêng file để kiểm tra tên người và tên tổ chức

**Comment by yuvayt** [comment]
https://github.com/undertheseanlp/underthesea đây nhé link github của underthesea đây ae vào đọc r làm nhé

**Comment by hao-prog** [comment]
> Chỉ cần có 1 file requeriment.txt của underthesea và runtime.txt cho python là được r cậu, xong mình có thể xây dựng riêng file để kiểm tra tên người và tên tổ chức

Là như này ý hả
-------------
![image](https://user-images.githubusercontent.com/72394775/103173900-7deb5f80-4890-11eb-8447-09ce34c2701a.png)
![image](https://user-images.githubusercontent.com/72394775/103173910-89d72180-4890-11eb-9265-0d6418e486be.png)

**Comment by yuvayt** [comment]
Đúng rồi!

**Comment by yuvayt** [comment]
![image](https://user-images.githubusercontent.com/68575750/103173772-d3733c80-488f-11eb-92e3-a45979699d51.png)
Còn đây là cách để gọi đến file python từ file js để kiểm tra tên nhé.

**Comment by GoiLaHoan** [comment]
Phần Entities trong wit.ai t thêm các Entity với keyword cụ thể đó, không biết có ổn không?

**Comment by GoiLaHoan** [comment]
> ## Anh Thành có bảo mình dùng fasttex để train bot đoán intent(ý định) của user nhưng t đọc thấy khó hiểu quá .T đang thử dùng wit.ai của Facebook để train bot đoán ý định của người dùng trong câu nói và thấy ổn phết ae ạ.
> ![image](https://user-images.githubusercontent.com/72394775/103173579-7e82f680-488e-11eb-808c-228914701d57.png)

https://wit.ai/apps/673596706642835
link wit.ai cho mọi người test nhé

**Comment by hao-prog** [comment]
> Phần Entities trong wit.ai t thêm các Entity với keyword cụ thể đó, không biết có ổn không?

T thấy cũng nhận diện khá tốt, ngắn gọn, đỡ phải train nhiều đấy nhỉ. Nhưng mà t đang gửi tin nhắn chứa link fb thì nó lại đang hiểu nhầm là có entity "greeting". Chắc tạm thời t dùng intent thôi đã.

**Comment by GoiLaHoan** [comment]
Vậy tạm thời t xóa hết Entities đi nhé, mn lập acc wit.ai để t thêm vào training con bot.

**Comment by hao-prog** [comment]
> > ## Anh Thành có bảo mình dùng fasttex để train bot đoán intent(ý định) của user nhưng t đọc thấy khó hiểu quá .T đang thử dùng wit.ai của Facebook để train bot đoán ý định của người dùng trong câu nói và thấy ổn phết ae ạ.
> > ![image](https://user-images.githubusercontent.com/72394775/103173579-7e82f680-488e-11eb-808c-228914701d57.png)
> 
> https://wit.ai/apps/673596706642835
> link wit.ai cho mọi người test nhé

hmm, chắc phải train thêm cho bot thôi
--------------------
![image](https://user-images.githubusercontent.com/72394775/103174105-03234400-4892-11eb-9ae5-6a57de468696.png)
![image](https://user-images.githubusercontent.com/72394775/103174135-34037900-4892-11eb-8d5c-d196c32898de.png)

**Comment by GoiLaHoan** [comment]
ừa, mình train dần dần, cố gắng để Confidence lên 70% là đc

**Comment by hao-prog** [comment]
> Vậy tạm thời t xóa hết Entities đi nhé, mn lập acc wit.ai để t thêm vào training con bot.

Uh có j để sau nếu còn thời gian thì có thể dùng Entities để cải tiến thêm. Ví dụ user nói: "Xin chào, tôi là Nguyễn Khắc Bấc" thì mình sẽ cần nhận diện được trong câu nói của người dùng có entity là tên người( Nguyễn Khắc Bấc) để các câu hỏi tiếp tránh hỏi tên vì có thể sẽ khiến user khó chịu...
