### ISSUE TITLE
Get data of conversations of a Fanpage

### ISSUE THREAD

**Issue by hao-prog** [Y2eVen/SE04-Nhom24.2#7]

**Comment by hao-prog** [comment]
T đóng issue này vì không cần phải lấy dữ liệu các cuộc hội thoại từ 1 Fanpage như anh bảo nữa nhé.

**Comment by yuvayt** [comment]
Ok

**Comment by yuvayt** [comment]
Mình sẽ cần nêu lại goal trong readme do mục đích đã khác trước đó

**Comment by hao-prog** [comment]
Ok
